### ISSUE TITLE
Handle the @Push annotation correctly

### ISSUE THREAD

**Issue by tamasmak** [vaadin/appsec-kit#132]
The `@Push` annotation is used on a view class instead of an `AppShellConfigurator` class. This prevents AppSec Kit to run with non Spring-Boot applications.
```
Found app shell configuration annotations in non `AppShellConfigurator` classes.
Please create a custom class implementing `AppShellConfigurator` and move the following annotations to it:
- @Push from com.vaadin.appsec.views.AppSecView
```
Verify the use of the @Push annotation in each version. Create a solution to detect if it is already used in an application, if not, then use it.

**Comment by Legioth** [comment]
Rather than relying on the `@Push` annotation, you could also consider toggling the setting programmatically using `someUi.getPushConfiguration().setPushMode(desiredMode);`

**Comment by heruan** [comment]
We can approach this like we do in Collaboration Kit: [ComponentConnectionContext.java#L313-L348](https://github.com/vaadin/collaboration-engine-internal/blob/c83172e221f0ec1d29cafee112100a63ffc2d15c/collaboration-engine/src/main/java/com/vaadin/collaborationengine/ComponentConnectionContext.java#L313-L348)
