### ISSUE TITLE
AppSecUtils.getVulnDepName fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dex-ds** [vaadin/appsec-kit#173]
because there is no validation of depName possible to split
Version 3.1.0

![image](https://github.com/vaadin/appsec-kit/assets/18628242/048d641d-ef22-4b59-8c69-e806aafa6c1c)

**Comment by dex-ds** [comment]
Hey vaadin, your commercial add-on needs love!
More Details => your OpenSourceVulnerabilityClient receives Affected json parts like this
![image](https://github.com/vaadin/appsec-kit/assets/18628242/a05553ca-16a4-498e-898c-d5cb7307b7eb)
Maybe here starts thing...

**Comment by tamasmak** [comment]
@dex-ds This issue has been fixed in the [3.2.1](https://github.com/vaadin/appsec-kit/releases/tag/3.2.1) version.
