### ISSUE TITLE
Identify a open-source tool for SBOM generation

### ISSUE THREAD

**Issue by heruan** [vaadin/appsec-kit#3]
There are existing open-source tools that help generating an SBOM (Software Bill Of Materials), i.e. a comprehensive view of all the direct and transitive dependencies used in an app.

We need to identify a suitable candidate among these tool that fulfills our requirements:
- the tool should be open-source
- the tool should be actively maintained
- the tool should generate a list of Java artifacts identified by ID and version

**Comment by tamasmak** [comment]
Based on research on the internet and finding some useful articles and repositories

https://github.com/awesomeSBOM/awesome-sbom
https://mergebase.com/best-tools-for-generating-sbom/#Snyk_via_snyk2spdx_optional_tool
https://snyk.io/blog/create-sboms-java-maven-gradle

which summarizes the most popular SBOM generation tools I collected this list of tools.

Comparing the tools based on the support they can provide the CycloneDX has the most benefits. It has a Maven and Gradle plugin, and a CLI tool too. It also has Java module which supports the SBOM handling if needed.

# CycloneDX

- Available Maven and Gradle plugins
- CycloneDX Core (Java) module
- Command line tool cdxgen
- Supported schemas:
  - CycloneDX (JSON / XML)
- Includes transitive dependencies

### CycloneDX CycloneDX Core (Java) module:

The CycloneDX core module provides a model representation of the SBOM along with utilities to assist in creating, validating, and parsing SBOMs. CycloneDX is a lightweight software bill of materials (SBOM) specification designed for use in application security contexts and supply chain component analysis.

- GitHub:
https://github.com/CycloneDX/cyclonedx-core-java
- Documentation:
https://cyclonedx.github.io/cyclonedx-core-java

### Links

- CycloneDX:
https://cyclonedx.org/specification/overview/
- How to use the Maven plugin:
https://github.com/CycloneDX/cyclonedx-maven-plugin
- CycloneDX Maven plugin documentation:
https://cyclonedx.github.io/cyclonedx-maven-plugin/index.html#
- CycloneDX cdxgen command line tool:
https://github.com/CycloneDX/cdxgen
- CycloneDX Gradle plugin:
https://github.com/CycloneDX/cyclonedx-gradle-plugin

# Syft

- Command line tool
- Format conversion
- Supported schemas:
  - JSON
  - text: A row-oriented, human-and-machine-friendly output
  - cyclonedx-xml
  - cyclonedx-json
  - spdx-tag-value: A tag-value formatted report conforming to the SPDX specification
  - spdx-json: A JSON report conforming to the SPDX JSON Schema
  - github: A JSON report conforming to GitHub's dependency snapshot format
  - table: A columnar summary (default)
  - template: User specified output format

Generating SBOM from project's root in syft and spdx formats:
```
syft <PROJECT_DIRECTORY> -o json=sbom.syft.json -o spdx-json=sbom.spdx.json
```

### Links
- Documentation:
https://github.com/anchore/syft

# SPDX (SBOM) Generator

- Command line tool
- Supported schemas:
  - SPDX 2.2 (default format)
  - JSON
  - RDF (in progress)

Generating SBOM from project's root with spdx-sbom-generator:

SPDX format:
```
spdx-sbom-generator -o /out/diretory/
```
JSON format:
```
spdx-sbom-generator -o /out/diretory/ -f json
```

### Links
- Documentation:
https://github.com/opensbom-generator/spdx-sbom-generator

# Microsoft sbom-tool

- Command line tool
- Supported schemas:
    - SPDX 2.2 (JSON)

Generating SBOM from project's root with sbom-tool:
```
sbom-tool generate -b ./sbom/sbom-tool -bc . -pn Test -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose
```

### Links

- Documentation:
https://github.com/microsoft/sbom-tool
- CLI Reference:
https://github.com/microsoft/sbom-tool/blob/main/docs/sbom-tool-cli-reference.md
- GitHub actions:
https://github.com/microsoft/sbom-tool/blob/main/docs/setting-up-github-actions.md

# Trivy

- Command line tool
- Supported schemas:
  - CycloneDX (JSON)
  - SPDX (JSON)

Generating SBOM from project's root:
```
trivy fs --format cyclonedx --output trivy-cyclonedx-sbom.json <PROJECT_DIRETORY>
```
```
trivy fs --format spdx-json --output trivy-spdx-sbom.json <PROJECT_DIRETORY>
```

### Links

- https://github.com/aquasecurity/trivy
- How to install:
https://aquasecurity.github.io/trivy/v0.40/getting-started/installation/
- SBOM generation:
https://aquasecurity.github.io/trivy/v0.40/docs/sbom/
- SBOM scanning:
https://aquasecurity.github.io/trivy/v0.40/docs/target/sbom/

# Eclipse jbom

- Available Jar plugin
- Generates runtime and static SBOMs for local and remote Java apps
- Supported schemas:
    - CycloneDX (JSON)

Generating SBOM from project's root with jbom-1.2.1.jar:
```
java -jar jbom-1.2.1.jar -d <PROJECT_DIRETORY>
```

### Links

- Documentation:
https://github.com/eclipse/jbom

# SPDX

- Available Maven plugin
- Supported schemas:
  - SPDX

### Links

- Documentation:
https://github.com/spdx/spdx-maven-plugin

**Comment by heruan** [comment]
**CycloneDX** has been identified as the reference tool to generate the SBOM for AppSec Kit.
