### ISSUE TITLE
Create documentation for the kit

### ISSUE THREAD

**Issue by heruan** [vaadin/appsec-kit#41]
Proper documentation needs to be added to the V7 and V8 branches in https://github.com/vaadin/docs

It must include:

- Description of the kit (its purpose and features, the problem it solves)
- Subscription required to use it (and link to get more info on that)
- Getting started tutorial, no code needed:
  - adding the kit dependency
  - generating the SBOM
  - starting the app in debug/dev mode
  - screenshots of the UI
- Advanced topics:
  - custom path of the data file
  - custom executor for background/scheduled jobs

**Comment by heruan** [comment]
Let's also add documentation about using the CycloneDX Gradle plugin to generate the SBOM.

**Comment by tamasmak** [comment]
Advanced topics and some other improvements have been also added to the documentation. A documentation for CycloneDX Gradle plugin to generate the SBOM is not relevant as there is no official support for Gradle yet.
All the requirements for this ticket are fulfilled therefore I'm closing it.
